project_name: 'zxhl'   # 用户名

date: 2022-12-17  # 日期

user_name_list: # user_name_list
  - user_name: Tom
  - user_name: Jack
  - user_name: tinker

user_name_listB: # user_name_list
  - Tom
  - Jack
  - tinker

user_name_listC: # user_name_list
  name: Tom
  gender: boy

# dir
dir_list:
  data_save_dir: datasets
  trained_model_dir: trained_models
  tensorboard_log_dir: tensorboard_log
  results_dir: results
  models_dir: models

# date time
time_list:
  train_start_date: '2015-01-01'
  train_end_date: '2022-11-20'
  trade_start_date: '2022-11-21'
  trade_end_date: '2022-12-28'
  time_interval: 1d

# data
curent_data_source: 'tushare'

ticker_list:
  - '600009.SH'
#  - '600016.SH'
#  - '600028.SH'

indicators:
  - 'macd'
  - 'boll_ub'
  - 'boll_lb'
  - 'rsi_30'
  - 'cci_30'
  - 'dx_30'
  - 'close_30_sma'
  - 'close_60_sma'

factors: #  - 'fft'
  - 'bias_5_days'
  - 'roc_6_days'
  - 'vstd_10_days'

# env
env_kwargs_a:
  hmax: 1000
  initial_amount: 1000000
  buy_cost_pct: 6.87e-5
  sell_cost_pct: 1.0687e-3
  reward_scaling: 1e-4
  state_space: state_space
  action_space: stock_dimension
  tech_indicator_list: config.INDICATORS
  print_verbosity: 1
  initial_buy: True
  hundred_each_trade: True

# agent
models:
  - A2C
  - DDPG
  - TD3
  - SAC
  - PPO

curent_model: A2C #{"a2c": A2C, "ddpg": DDPG, "td3": TD3, "sac": SAC, "ppo": PPO}


#model_file_name

